### Send POST request with json body Test login API
# @no-cookie-jar
POST http://127.0.0.1:8080/v1/user/login
Content-Type: application/json

{
  "username": "gaidihu@qq.com",
  "password": "123456"
}


### Send POST request with json body Test register API
# @no-cookie-jar
POST http://127.0.0.1:8080/v1/user/register
Content-Type: application/json

{
  "name": "luckyboy",
  "password": "xiaoming123..",
  "email": "1750930311@qq.com"
}

### Send POST request with json body Test login verification Code API
# @no-cookie-jar
POST http://127.0.0.1:8080/v1/user/code
Content-Type: application/json

{
  "email": "1750930322@qq.com"
}



### Send POST request with json body Test update album information API
# @no-cookie-jar
POST http://127.0.0.1:8080/v1/alb/update/album
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjkxMzIyODMsInVzZXJuYW1lIjoiaGJjbWNjX3VzZXIwMUA1MWp6Y2xvdWQuY29tIn0.e-cJfOalH8SKzr6TmLPNaaszG0fganf8ljMq-VwDSno

{}