mysql:
  host: "127.0.0.1"
  port: 3306
  user: "anhui"
  password: "55w95dtNb"
  dbname: "d_s_hwj"
  max_open_connects: 200
  max_idle_connects: 50

redis:
  host: "127.0.0.1"
  port: "6379"
  db: 0,
  pool: 10


cookies:
  cook_path: "/v1/user/login"
  cook_ip: "127.0.0.1"


login_auth:
  secret_key: "384FJ./@ADJFAEWrerewori,,...@$*(^%"

log_file:
  log_path: "E:\\goPro\\goPro4\\logs\\logs.log"



email_config:
  smtp_host: "smtp.qq.com"
  smtp_port: 465
  smtp_user: "jackgeng1314@qq.com"
  smtp_pass: "frmnctgttqdddhce"